name: gamenect_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  multi_select_flutter: ^4.1.3
  dropdown_search: ^6.0.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.2

  # Firebase Core & Authentication
  
  rxdart: ^0.28.0
  # Firebase Services
  cloud_firestore: ^5.4.3               
  cloud_functions: ^5.1.3               
  firebase_messaging: ^15.1.3 
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_crashlytics: ^4.3.9
  firebase_analytics: ^11.5.2
  firebase_storage: ^12.4.9
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1

  # State Management & HTTP
  provider: ^6.1.2
  http: ^1.2.2

  # Configuration
  flutter_dotenv: ^6.0.0

  # Machine Learning
  tflite_flutter: ^0.11.0

  # RTC
  agora_rtc_engine: ^6.5.2
  permission_handler: ^12.0.1
  intl_phone_number_input: ^0.7.3

  #camera & video
  camera: ^0.11.0+6
  video_player: ^2.8.1
  camerawesome: ^2.5.0
  video_thumbnail: ^0.5.3
  flutter_sound: ^9.2.13
  path_provider: ^2.0.15
  #log
  logger: ^2.2.0
  #Payment
  crypto: ^3.0.3
  url_launcher: ^6.2.1
  flutter_web_browser: ^0.17.1

  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cached_network_image: ^3.3.1
  logging : ^1.3.0
  image_picker: ^1.1.2
  flutter_swiper_null_safety: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/gamenect_logo.png
    - assets/images/google_logo.png
    - assets/images/yacht_bg.jpg
